### ISSUE TITLE
Precedence of operators in calculating modifiers

### ISSUE THREAD

**Issue by mrngm** [thijsmie/tantalus#3]
https://github.com/thijsmie/tantalus/blob/5fb666d7fd179b8e7883af381466eac7b51bbcb7/ndbextensions/models.py#L65
https://github.com/thijsmie/tantalus/blob/5fb666d7fd179b8e7883af381466eac7b51bbcb7/ndbextensions/models.py#L68

Are you sure these precedence of operators are correct? The `pre_add` suggests an addition is done on `line.value`, similarly for `post_add`.

This causes serious calculation errors (example of line 65; the last column is probably incorrect, but shows the effect of braces). I think the following formula is correct: 

```python
((line.value + self.pre_add) (*/) self.multiplier + self.post_add)*line.amount
```

![2017-10-20-181253_701x204_scrot](https://user-images.githubusercontent.com/305101/31831035-5037b7f0-b5c2-11e7-8a72-1ce2fbde8be8.png)

**Comment by thijsmie** [comment]
The value of a line is always its total amount and thus does not need to be multiplied, while an addition is define per item so does need multiplication, so I'm quite convinced my formula is correct.
